name-template: 'Release ${{ nextReleaseVersion }}'
tag-template: 'v${{ nextReleaseVersion }}'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🧪 Refactor'
    labels:
      - 'refactor'
change-template: '- ${{ change.title }} (#${{ change.number }})'
version-resolver:
  major:
    type: 'MAJOR'
  minor:
    type: 'MINOR'
  patch:
    type: 'PATCH'
  default: 'patch'
template: |
  ## What's Changed
  $CHANGES